In [1]:
#New data to change
import pandas as pd
import numpy as np

In [3]:
#New data to pivot
#Data taken by world bank:  https://data.worldbank.org/indicator/NY.GDP.MKTP.KD?name_desc=false
unpivoted_table = pd.read_csv(r"C:\Users\danie\Downloads\API_NY.GDP.MKTP.KD_DS2_en_csv_v2_135\real_gdp_data.csv")

In [13]:
unpivoted_table1=unpivoted_table.drop(columns = ["Indicator Name", "Indicator Code"])
unpivoted_table1.head()

,Country Name,Country Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,China,CHN,1.610230e+11,1.171120e+11,1.105770e+11,1.219670e+11,1.441400e+11,1.685720e+11,1.865250e+11,1.757620e+11,...,1.204520e+13,1.287520e+13,1.374520e+13,1.457930e+13,1.492050e+13,1.619920e+13,1.670690e+13,1.761150e+13,1.848810e+13,NaN
1,France,FRA,5.109280e+11,5.362010e+11,5.729640e+11,6.079340e+11,6.479530e+11,6.793060e+11,7.143820e+11,7.486850e+11,...,2.463490e+12,2.514820e+12,2.556210e+12,2.608040e+12,2.413980e+12,2.580120e+12,2.650220e+12,2.688360e+12,2.720360e+12,NaN
2,Germany,DEU,9.179730e+11,9.574320e+11,1.001700e+12,1.029100e+12,1.097420e+12,1.154980e+12,1.187460e+12,1.183530e+12,...,3.501210e+12,3.599170e+12,3.640050e+12,3.675640e+12,3.523760e+12,3.661540e+12,3.727790e+12,3.695370e+12,3.677050e+12,NaN
3,Italy,ITA,4.885030e+11,5.285960e+11,5.613880e+11,5.928800e+11,6.094670e+11,6.293850e+11,6.670520e+11,7.149370e+11,...,1.868240e+12,1.898200e+12,1.913890e+12,1.922110e+12,1.751650e+12,1.908090e+12,2.000080e+12,2.019600e+12,2.033590e+12,NaN
4,Mexico,MEX,1.522530e+11,1.598650e+11,1.673220e+11,1.808870e+11,2.024220e+11,2.167940e+11,2.300100e+11,2.434770e+11,...,1.234800e+12,1.257910e+12,1.282720e+12,1.277680e+12,1.170940e+12,1.241770e+12,1.287840e+12,1.331020e+12,1.350020e+12,NaN

In [15]:
#Thank god for AI 
# Transform from wide to long format
pivoted_table = unpivoted_table1.melt(
    id_vars=['Country Name', 'Country Code'], # Columns to keep as they are
    var_name='Year',                          # New column name for the years
    value_name='Real GDP (2015 $)'            # New column name for the GDP values
)

In [17]:
pivoted_table

      Country Name Country Code  Year  Real GDP (2015 $)
0            China          CHN  1960       1.610230e+11
1           France          FRA  1960       5.109280e+11
2          Germany          DEU  1960       9.179730e+11
3            Italy          ITA  1960       4.885030e+11
4           Mexico          MEX  1960       1.522530e+11
..             ...          ...   ...                ...
391         France          FRA  2025                NaN
392        Germany          DEU  2025                NaN
393          Italy          ITA  2025                NaN
394         Mexico          MEX  2025                NaN
395  United States          USA  2025                NaN

[396 rows x 4 columns]

In [21]:
#Now send out the data:
pivoted_table.to_csv(r"C:\Users\danie\Downloads\real_gdp_data_six_countries.csv", index= False)